### ISSUE TITLE
There is any plan optimize daloradius to suitable for PHP7?

### ISSUE THREAD

**Issue by terencechuen** [lirantal/daloradius#3] opened 2016-06-06 14:40 UTC
Hi this is a excellent tool for radius management.

But in PHP7 it have many error because of some function has been removed.

There is any plan optimize daloradius to suitable for PHP7?

If yes,please let me know.
If no,can I fixes it by myself?

**Comment by lirantal** [comment] 2016-06-06 14:44
Hey @terencechuen,

This is awesome that you are pinging me on this and offering to help.

I don't use daloRADIUS day to day anymore like I did before so it's hard for me to maintain it on a regular basis but if you are willing to help out and take this task then all credit goes to you and I'll be 100% dedicated to helping you and working on getting daloRADIUS up to date.

So are you in? :)

**Comment by terencechuen** [comment] 2016-06-06 15:14
Yes!

My php skill level is not very good,it make take a long time to fix it.

I already planned spend 3 hours every night to collect error log and try to fix, because I have four clients use it on they server.

I can take this opportunity to learn php, my areas of focus is KVM virtualization

I will share this wonderful project with my friends.

To be honest,in linux environment it is very important tool to manage radius.

**Comment by terencechuen** [comment] 2016-06-07 12:48
Hello @lirantal 

I do not know much about github, should I press the "New pull request"  or "Fork" ?

**Comment by mfaroukg** [comment] 2016-06-09 08:35
I can learn and help also since i like daloradius also

**Comment by lirantal** [comment] 2016-06-15 16:15
Hi @terencechuen, @mfaroukg,

I'd love to get some help on this.
Did any of you made any progress in getting this to work? Can you share some logs/errors that you are getting?

**Comment by mfaroukg** [comment] 2016-06-16 00:33
Hi @lirantal 
I am following the freeradius development news to see the difference since daloradius  more connected to old freeradius 2.1.2, there should be somethings to be fixed in the database to follow the new freeradius.
If you have thought about this part please share with us your ideas to start in this branch.
I will share later the output of the old daloradius when i am able to reproduce it.

**Comment by lirantal** [comment] 2016-06-16 07:33
I don't have a running FreeRADIUS environment anymore, and if I did, it is quite hard to test it efficiently as I don't do the hotspots/wifi logins thing anymore.

I would like to help you guys contribute to daloRADIUS and make the proper changes so let me know if you have specific questions.

**Comment by terencechuen** [comment] 2016-06-16 07:41
I did,I running running FreeRADIUS on centos 7,and centos 7 can install FreeRADIUS 3 via yum only.
I have 3 server running FreeRADIUS, I will try my best to fix some issues.
At the same I try Constructing New Control Interface, but it may take a long time. ^_^

My native language is chinese and my english is not good, if there have any offended, please tell me.

**Comment by terencechuen** [comment] 2016-06-16 08:05
hello @mfaroukg 
can you share you log or describe the problem for more detail?
I running freeRADIUS 3 right now, I has been fixed some issues but I did not make a record .
if you can provide description of the problem, it is great help to me to fix daloradius.

**Comment by lirantal** [comment] 2016-06-16 12:02
No offense, you're great! :)

**Comment by mfaroukg** [comment] 2016-06-16 23:40
hi @terencechuen 
I am suggesting to open another case with your configuration for this so others can also get the knowledge.
@lirantal can you guide us how to share our configuration in our forks and you merge to master.

**Comment by henderbj** [comment] 2016-06-18 03:57
Hi, all.
@mfaroukg, if you are asking how to upload changes from your working directory to your fork repository, please just follow any git tutorial.
In short, is something like:
$ cd daloradius
$ git status (to see which files have changed)
$ git diff (to see actual changes on every file)
$ git add <changed-files>
$ git commit -m "Describe what did change on these files"
And repeat for rest of changes
Please protect your private configuration, like passwords, IP, hostnames, domains, etc. Avoid them to get into repository. Again, please refer to any git tutorial. This is one more specific to our needs, from github:
https://guides.github.com/activities/hello-world/

**Comment by lirantal** [comment] 2016-07-08 20:07
Hi Everyone ( @terencechuen , @mfaroukg , @henderbj , @dennisdegreef ),

Can you please check my instructions in issue #5 which describe how to get daloRADIUS  running in PHP 7?

Let me know if you still experience any issues or have further questions.
Thanks!

**Comment by terencechuen** [comment] 2016-07-09 03:18
@lirantal sure,the instructions is correct.
Modify mysql configuration from mysql to mysqli is primary.

I still working on it,but last month is a busy month.

**Comment by kkwised** [comment] 2016-07-18 12:55
Hi,
I'm also In!  First day on GitHub.  I could contribute too :)

**Comment by lirantal** [comment] 2016-07-19 20:22
Thanks for the will to help and join in @kkwised!
It turned out that adding PHP 7 support wasn't that big of an issue - I documented it in this open issue: https://github.com/lirantal/daloradius/issues/5

If you're willing to work on other items in daloRADIUS I can offer some areas to begin with :)

**Comment by kkwised** [comment] 2016-07-20 02:16
Thanks! Just show me what to do and I'll be happy to help

**Comment by lirantal** [comment] 2016-08-27 15:09
Hey guys, we already have a PR and a global issue for the compatibility with PHP 7 so I'm closing this one.

**Closed by lirantal** 2016-08-27 15:09 UTC
