### ISSUE TITLE
server status and information not showing up

### ISSUE THREAD

**Issue by HuNapoji** [lirantal/daloradius#343] opened 2023-01-22 12:02 UTC
Hi,

I have installed and configured daloradius on Ubuntu and was able to login and use it.

However when I try to check the Server Status and Information menu I'm getting this error message in the error.log,

[Sun Jan 22 12:00:30.246778 2023] [php:error] [pid 31490] [client 10.211.132.66:58581] PHP Fatal error:  Uncaught Error: Call to undefined function each() in /var/www/html/daloradius/library/exten-server_info.php:164\nStack trace:\n#0 /var/www/html/daloradius/library/exten-server_info.php(278): get_memory()\n#1 /var/www/html/daloradius/rep-stat-server.php(46): include('...')\n#2 {main}\n  thrown in /var/www/html/daloradius/library/exten-server_info.php on line 164, referer: http://X.X.X.X/daloradius/rep-stat-server.php

Any idea what can be the issue?

Thank you in advance.

Best Regards,

Erik Molnar

**Comment by filippolauria** [comment] 2023-01-23 11:42
Hi Erik,
thanks to your `error.log` output, I was able to fix the issue with my last merged PR ( #344 ).

The problem was caused by the use of [each](https://www.php.net/manual/en/function.each.php) - which has been deprecated in the latest versions of PHP - in the daloRADIUS `get_memory()` function.

**Closed** 2023-02-24 09:30 UTC
Labels: bug
